name: GitHub Contribution Snake

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate contribution snake
        uses: DenverCoder1/github-readme-snake-action@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: 'output/github-contribution-grid-snake.svg'
      - name: Commit SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update contribution snake"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
